@url = https://solid-space-carnival-6jxv97x4wq7crj94-8080.app.github.dev/alunos

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBZmVyaWNvZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjM5NjI0OTJ9.TVRT8fF0PuROcd5_tYE3ztLa24vSkU1Ns6JkzA-2jfA

### 
GET {{url}}
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{url}}/1
Accept: application/json
Authorization: Bearer {{token}}

### 
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Kleber",
  "email": "kleber@example.com",
  "telefone": "+55123456789",
  "dataMatricula": "2024-06-01"
}

###

PUT {{url}}/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "telefone": "+55987654321"
}

###
DELETE {{url}}/7
Accept: application/json
Authorization: Bearer {{token}}