@url = https://solid-space-carnival-6jxv97x4wq7crj94-8080.app.github.dev/cursos

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBZmVyaWNvZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjM5NjI0OTJ9.TVRT8fF0PuROcd5_tYE3ztLa24vSkU1Ns6JkzA-2jfA

###
GET {{url}}
Accept: application/json
Authorization: Bearer {{token}}
###
GET {{url}}/1
Accept: application/json
Authorization: Bearer {{token}}

### 
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Big Data no Agronegócio",
    "descricao": "Ciência de Dados para o Agronegócio",
    "cargaHoraria": 2500,
    "status": "ATIVO",
    "dataCriacao": "2017-01-01T00:00:00"
}

###
PUT {{url}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "Encerrado"
}

### 
DELETE {{url}}/3
Accept: application/json
Authorization: Bearer {{token}}